# MongoDB Atlas connection
spring.data.mongodb.uri=mongodb+srv://ap211_db_user:d9yvvZWNAILxNRcd@db1.svkbxlh.mongodb.net/?appName=db1

# This tells Spring Boot which database to use inside the cluster
spring.data.mongodb.database=shms_db

spring.application.name=hostel-management
server.port=8080
